<?php

/**
 * @file
 * Contains jdf_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jdf_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jdf_custom module.
    case 'help.page.jdf_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom stuff for jdf.com') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function jdf_custom_theme() {
  return [
    'jdf_custom' => [
      'render element' => 'children',
    ],
  ];
}
